//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//     
//     Generation parameters:
//     - DataFilename: Patterns\Thai\Thai-DateTime.yaml
//     - Language: Thai
//     - ClassName: DateTimeDefinitions
// </auto-generated>
//------------------------------------------------------------------------------
namespace Microsoft.Recognizers.Definitions.Thai
{
	using System;
	using System.Collections.Generic;

	public static class DateTimeDefinitions
	{
		public const string TillRegex = @"(?<till>ถึง|จนถึง|ไป\s*จนถึง|--|-|—|——|~)";
		public const string RangeConnectorRegex = @"(?<and>และ|กับ|ถึง|ถึง\s*ช่วง|จนถึง|ไป\s*จนถึง|--|-|—|——)";
		public const string RelativeRegex = @"(?<order>หน้า|ถัดไป|ต่อไป|ที่\s*จะ\s*ถึง|ที่\s*กำลัง\s*จะ\s*ถึง|ที่\s*จะ\s*มา\s*ถึง|ที่\s*กำลัง\s*จะ\s*มา\s*ถึง|ก่อน\s*หน้า|ก่อน|ที่\s*แล้ว|ที่\s*ผ่าน\s*มา|นี้|ปัจจุบัน)";
		public const string StrictRelativeRegex = @"(?<order>หน้า|ถัดไป|ต่อไป|ที่\s*จะ\s*ถึง|ที่\s*กำลัง\s*จะ\s*ถึง|ที่\s*จะ\s*มา\s*ถึง|ที่\s*กำลัง\s*จะ\s*มา\s*ถึง|ก่อน\s*หน้า|ก่อน|ที่\s*แล้ว|ที่\s*ผ่าน\s*มา|นี้|ปัจจุบัน)";
		public const string NextPrefixRegex = @"(หน้า|ถัดไป|ต่อไป|ที่\s*จะ\s*ถึง|ที่\s*กำลัง จะ ถึง|ที่\s*จะ\s*มา\s*ถึง|ที่\s*กำลัง\s*จะ\s*มา\s*ถึง)";
		public static readonly string AfterNextSuffixRegex = $@"(หลัง\s*จาก\s*({WrittenMonthRegex}|{DateUnitRegex}|{RangeUnitRegex}|{DurationUnitRegex}|{WeekDayRegex}|{SingleWeekDayRegex})(ถัดไป|ต่อไป|หน้า))";
		public const string PastPrefixRegex = @"(ก่อน\s*หน้า|ก่อน|ที่\s*แล้ว|ที่\s*ผ่าน\s*มา)";
		public const string ThisPrefixRegex = @"(นี้|ปัจจุบัน)";
		public const string CenturySuffixRegex = @"(^century)";
		public const string ReferencePrefixRegex = @"(นั้น|เดียวกัน)";
		public const string FutureSuffixRegex = @"(ใน\s*)?(อนาคต|จาก\s*นี้\s*ไป|ต่อจากนี้\s*ไป|ตั้งแต่\s*นี้\s*ไป|ต่อ\s*แต่\s*นี้\s*ไป|ตั้งแต่\s*นี้\s*ต่อไป|นับจากนี้\s*ไป|นับ\s*แต่\s*นี้\s*ไป)";
		public const string DayRegex = @"(วัน\s*ที่\s*)?\b(?<day>01|02|03|04|05|06|07|08|09|10th|10|11th|11st|11|12nd|12th|12|13rd|13th|13|14th|14|15th|15|16th|16|17th|17|18th|18|19th|19|1st|1|20th|20|21st|21th|21|22nd|22th|22|23rd|23th|23|24th|24|25th|25|26th|26|27th|27|28th|28|29th|29|2nd|2|30th|30|31st|31|3rd|3|4th|4|5th|5|6th|6|7th|7|8th|8|9th|9)(?=\b|t)";
		public const string MonthNumRegex = @"(เดือน\s*)?\b(?<month>01|02|03|04|05|06|07|08|09|10|11|12|1|2|3|4|5|6|7|8|9)\b";
		public const string CenturyRegex = @"(?<century>((หนึ่ง|สอง)\s*พัน(\s*(หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า)\s*ร้อย)?)|((หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า)\s*(ร้อย)))";
		public const string WrittenNumRegex = @"(เอ็ด|หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า|สิบ|สิบ\s*เอ็ด|สิบ\s*สอง|สิบ\s*สาม|สิบ\s*สี่|สิบ\s*ห้า|สิบ\s*หก|สิบ\s*เจ็ด|สิบ\s*แปด|สิบ\s*เก้า|ยี่\s*สิบ|สาม\s*สิบ|สี่\s*สิบ|ห้า\s*สิบ|หก\s*สิบ|เจ็ด\s*สิบ|แปด\s*สิบ|เก้า\s*สิบ)";
		public static readonly string FullTextYearRegex = $@"(((ปี|ค\.?ศ\.?|พ\.?ศ\.?)\s*)?((?<firsttwoyearnum>{CenturyRegex})\s*(?<lasttwoyearnum>((สิบ|ยี่\s*สิบ|สาม\s*สิบ|สี่\s*สิบ|ห้า\s*สิบ|หก\s*สิบ|เจ็ด\s*สิบ|แปด\s*สิบ|เก้า\s*สิบ)(\s*(เอ็ด|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า))?)|{WrittenNumRegex})|(?<firsttwoyearnum>{CenturyRegex})|(?<fouryearnum>(หนึ่ง|สอง)\s*((ศูนย์|หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า)\s*){{3}})))";
		public const string YearNumRegex = @"((((ปี|ค\.?ศ\.?)\s*)?(?<year>((1[5-9]|20)\d{2})|2100))|(((ปี|พ\.?ศ\.?)\s*)?(?<year>2[2-5]\d{2}|26[0-3][0-9]|264[0-3])))";
		public static readonly string YearRegex = $@"({YearNumRegex}|{FullTextYearRegex})";
		public const string WeekDayRegex = @"(?<weekday>(วัน\s*)?(อาทิตย์|อาทิต|อาทิด|จันทร์|จัน|อังคาร|พุธ|พุด|พฤหัสบดี|พฤหัส|ศุกร์|ศุก|เสาร์|อา\.|จ\.|อ\.|พ\.|พฤ\.|ศ\.|ส\.))";
		public const string SingleWeekDayRegex = @"(?<weekday>(วัน\s*)?(อาทิตย์|อาทิต|อาทิด|จันทร์|จัน|อังคาร|พุธ|พุด|พฤหัสบดี|พฤหัส|ศุกร์|ศุก|เสาร์|อา\.|จ\.|อ\.|พ\.|พฤ\.|ศ\.|ส\.))";
		public static readonly string RelativeMonthRegex = $@"(?<relmonth>(ของ\s*)?เดือน\s*{RelativeRegex})";
		public const string WrittenMonthRegex = @"(เดือน\s*)?(?<month>เมษายน|พฤษภาคม|มิถุนายน|กรกฎาคม|สิงหาคม|กันยายน|ตุลาคม|พฤศจิกายน|ธันวาคม|มกราคม|กุมภาพันธ์|มีนาคม|เมษา|พฤษภา|มิถุนา|กรกฎา|สิงหา|กันยา|ตุลา|พฤศจิกา|พฤศจิ|ธันวา|มกรา|กุมภา|มีนา|เม\.?ย\.?|พ\.?ค\.?|มิ\.?ย\.?|ก\.?ค\.?|ส\.?ค\.?|ก\.?ย\.?|ต\.?ค\.?|พ\.?ย\.?|ธ\.?ค\.?|ม\.?ค\.?|ก\.?พ\.?|มี\.?ค\.?)";
		public static readonly string MonthSuffixRegex = $@"(?<msuf>((ใน|ของ|ตอน)\s*)?({RelativeMonthRegex}|{WrittenMonthRegex}))";
		public const string DateUnitRegex = @"(?<unit>ปี|เดือน|สัปดาห์|วีค|อาทิตย์|วัน)";
		public static readonly string SimpleCasesRegex = $@"((จาก|ตั้งแต่|ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)?({DayRegex})\s*{TillRegex}\s*({DayRegex}\s*{MonthSuffixRegex}|{MonthSuffixRegex}\s*{DayRegex})((\s*|\s*,\s*){YearRegex})?";
		public static readonly string MonthFrontSimpleCasesRegex = $@"((จาก|ตั้งแต่|ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)?{MonthSuffixRegex}\s*((จาก|ตั้งแต่|ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)?({DayRegex})\s*{TillRegex}\s*({DayRegex})((\s*|\s*,\s*){YearRegex})?";
		public static readonly string MonthFrontBetweenRegex = $@"({MonthSuffixRegex})\s*((ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)({DayRegex})\s*{RangeConnectorRegex}\s*({DayRegex})((\s*|\s*,\s*){YearRegex})?";
		public static readonly string BetweenRegex = $@"((ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)({DayRegex})\s*{RangeConnectorRegex}\s*({DayRegex})\s*{MonthSuffixRegex}((\s*|\s*,\s*){YearRegex})?";
		public static readonly string MonthWithYear = $@"(({WrittenMonthRegex}(\s*),?(\s*(ของ|ใน))?(\s*)({YearRegex}|ปี\s*(?<order>หน้า|ถัดไป|ต่อไป|ก่อน\s*หน้า|ก่อน|ที่\s*แล้ว|ที่\s*ผ่าน\s*มา|นี้)))|(({YearRegex}|ปี\s*(?<order>หน้า|ถัดไป|ต่อไป|ก่อน\s*หน้า|ก่อน|ที่\s*แล้ว|ที่\s*ผ่าน\s*มา|นี้))(\s*),?(\s*){WrittenMonthRegex}))";
		public static readonly string OneWordPeriodRegex = $@"(((เดือน\s*)?(?<month>เมษายน|พฤษภาคม|มิถุนายน|กรกฎาคม|สิงหาคม|กันยายน|ตุลาคม|พฤศจิกายน|ธันวาคม|มกราคม|กุมภาพันธ์|มีนาคม|เมษา|พฤษภา|มิถุนา|กรกฎา|สิงหา|กันยา|ตุลา|พฤศจิกา|พฤศจิ|ธันวา|มกรา|กุมภา|มีนา|เม\.?ย\.?|พ\.?ค\.?|มิ\.?ย\.?|ก\.?ค\.?|ส\.?ค\.?|ก\.?ย\.?|ต\.?ค\.?|พ\.?ย\.?|ธ\.?ค\.?|ม\.?ค\.?|ก\.?พ\.?|มี\.?ค\.?)({StrictRelativeRegex}\s*)?)|ตั้งแต่\s*ต้น\s*(เดือน|ปี)\s*จนถึง\s*วัน\s*นี้|(สุด\s*สัปดาห์|สัปดาห์|สัปดา|อาทิตย์|วีค|เดือน|ปี)(\s*{RelativeRegex}\s*)?(\s*{AfterNextSuffixRegex})?)";
		public static readonly string MonthNumWithYear = $@"({YearNumRegex}(\s*)[/\-\.](\s*){MonthNumRegex})|({MonthNumRegex}(\s*)[/\-](\s*){YearNumRegex})";
		public static readonly string WeekOfMonthRegex = $@"(?<wom>(สัปดาห์|สัปดา|อาทิตย์|วีค)\s*(?<cardinal>แรก|ที่\s*(หนึ่ง|1)|ที่\s*(สอง|2)|ที่\s*(สาม|3)|ที่\s*(สี่|4)|ที่\s*(ห้า|5)|สุดท้าย)\s*{MonthSuffixRegex})";
		public static readonly string WeekOfYearRegex = $@"(?<woy>(สัปดาห์|สัปดา|อาทิตย์|วีค)\s*(?<cardinal>แรก|ที่\s*(หนึ่ง|1)|ที่\s*(สอง|2)|ที่\s*(สาม|3)|ที่\s*(สี่|4)|ที่\s*(ห้า|5)|สุดท้าย)(\s*(ของ|ใน))?\s*({YearRegex}|ปี\s*{RelativeRegex}))";
		public static readonly string FollowedDateUnit = $@"({DateUnitRegex})";
		public static readonly string NumberCombinedWithDateUnit = $@"(?<num>\d+(\.\d*)?){DateUnitRegex}";
		public const string QuarterTermRegex = @"(((ไตรมาส|ไตรมาศ|ควอเตอร์|ควอร์เตอร์)\s*(?<cardinal>แรก|ที่\s*(หนึ่ง|1)|ที่\s*(สอง|2)|ที่\s*(สาม|3)|ที่\s*(สี่|4)))|(Q(?<number>[1-4])))";
		public static readonly string QuarterRegex = $@"({QuarterTermRegex})((\s*(ของ|ใน)|\s*,\s*)?\s*({YearRegex}|ปี\s*{RelativeRegex}))?";
		public static readonly string QuarterRegexYearFront = $@"({YearRegex}|ปี\s*{RelativeRegex})\s*{QuarterTermRegex}";
		public const string HalfYearTermRegex = @"ครึ่ง\s*ปี\s*(?<cardinal>แรก|ที่\s*(หนึ่ง|1)|ที่\s*(สอง|2))";
		public static readonly string HalfYearFrontRegex = $@"(?<year>((1[5-9]|20)\d{{2}})|2100)\s*H(?<number>[1-2])";
		public static readonly string HalfYearBackRegex = $@"(H(?<number>[1-2])|({HalfYearTermRegex}))(\s*(ของ|ใน)|\s*,\s*)?\s*({YearRegex})";
		public static readonly string HalfYearRelativeRegex = $@"({HalfYearTermRegex})(\s*(ของ|ใน)|\s*,\s*)?\s*(ปี\s*{RelativeRegex})";
		public static readonly string AllHalfYearRegex = $@"({HalfYearFrontRegex})|({HalfYearBackRegex})|({HalfYearRelativeRegex})";
		public const string EarlyPrefixRegex = @"(?<EarlyPrefix>ต้น|ตอน\s*ต้น|ช่วง\s*ต้น|ต้น\s*ๆ\s*|(?<RelEarly>(ช่วง\s*แรก|ระยะ\s*แรก|ระยะ\s*ต้น\s*ๆ\s*)(\s*(ใน|ของ))?))";
		public const string MidPrefixRegex = @"(?<MidPrefix>กลาง|ตอน\s*กลาง|ช่วง\s*กลาง|กลาง\s*ๆ\s*)";
		public const string LaterPrefixRegex = @"(?<LatePrefix>ปลาย|สิ้น|ท้าย|ตอน\s*ปลาย|ตอน\s*สิ้น|ตอน\s*ท้าย|ช่วง\s*ปลาย|ช่วง\s*สิ้น|ช่วง\s*ท้าย|จบ|ปลาย\s*ๆ\s*|(?<RelLate>(ตอน\s*ปลาย|ตอน\s*ท้าย|ช่วง\s*ปลาย|ช่วง\s*ท้าย)(\s*ของ)?))";
		public static readonly string PrefixPeriodRegex = $@"({EarlyPrefixRegex}|{MidPrefixRegex}|{LaterPrefixRegex})";
		public const string PrefixDayRegex = @"((?<EarlyPrefix>ต้น|ตอน\s*ต้น|ช่วง\s*ต้น|ต้น\s*ๆ\s*)|(?<MidPrefix>กลาง|ตอน\s*กลาง|ช่วง\s*กลาง|กลาง\s*ๆ\s*)|(?<LatePrefix>ปลาย|สิ้น|ท้าย|ตอน\s*สิ้น|ตอน\s*ท้าย|ช่วง\s*สิ้น|ช่วง\s*ท้าย|ปลาย\s*ๆ\s*|ท้าย\s*ๆ\s*))(\s*ของ)?(\s*วัน)?$";
		public const string SeasonDescRegex = @"(?<seas>(ฤดู\s*ใบไม้\s*ผลิ|หน้า\s*ร้อน|ฤดู\s*ร้อน|ฤดู\s*ใบไม้\s*ร่วง|หน้า\s*หนาว|ฤดู\s*หนาว|หน้า\s*ฝน|ฤดู\s*ฝน))";
		public static readonly string SeasonRegex = $@"(?<season>({PrefixPeriodRegex}\s*)?{SeasonDescRegex}(\s*{RelativeRegex})?((\s*(ของ|ใน)|\s*,\s*)?\s*({YearRegex}|ปี\s*{RelativeRegex}))?)";
		public const string WhichWeekRegex = @"((สัปดาห์|สัปดา|อาทิตย์|วีค)ที่)(\s*)(?<number>\d\d|\d|0\d)";
		public const string WeekOfRegex = @"(สัปดาห์|สัปดา|อาทิตย์|วีค)(\s*ของ)";
		public const string MonthOfRegex = @"(เดือน)(\s*ของ)";
		public const string MonthRegex = @"(เดือน\s*)?(?<month>เมษายน|พฤษภาคม|มิถุนายน|กรกฎาคม|สิงหาคม|กันยายน|ตุลาคม|พฤศจิกายน|ธันวาคม|มกราคม|กุมภาพันธ์|มีนาคม|เมษา|พฤษภา|มิถุนา|กรกฎา|สิงหา|กันยา|ตุลา|พฤศจิกา|พฤศจิ|ธันวา|มกรา|กุมภา|มีนา|เม\.?ย\.?|พ\.?ค\.?|มิ\.?ย\.?|ก\.?ค\.?|ส\.?ค\.?|ก\.?ย\.?|ต\.?ค\.?|พ\.?ย\.?|ธ\.?ค\.?|ม\.?ค\.?|ก\.?พ\.?|มี\.?ค\.?)";
		public const string AmbiguousMonthP0Regex = @"((^ขออนุญาตฉัน)|(ฉัน|คุณ|เขา|เธอ|เรา|พวกเขา)\s*อาจ(จะ)?|(อาจ(จะ)?\s*((((ไม่่)\s*)?(เป็น|รวม|ใช้|มี|ส่งผล|เกี่ยว|ได้))|(หรืออาจไม่ใช่))))";
		public const string AmDescRegex = @"(am\b|a\.m\.|a m\b|a\. m\.|a\.m\b|a\. m\b|a m\b)";
		public const string PmDescRegex = @"(pm\b|p\.m\.|p\b|p m\b|p\. m\.|p\.m\b|p\. m\b|p m\b)";
		public static readonly string DateYearRegex = $@"(((ปี|ค\.?ศ\.?)\s*)?(?<year>((1\d|20)\d{{2}})|2100|([0-27-9]\d\b(?!(\s*((\:)|{AmDescRegex}|{PmDescRegex}|(นาฬิกา|น|น.|โมง))))))|((ปี|พ\.?ศ\.?)\s*)?(?<year>(2[2-5])\d{{2}}|26[0-3]\d|264[0-3]|([1-7]\d\b(?!(\s*((\:)|{AmDescRegex}|{PmDescRegex}|(นาฬิกา|น|น.|โมง)))))))";
		public static readonly string YearSuffix = $@"(,?\s*({DateYearRegex}|{FullTextYearRegex}))";
		public static readonly string OnRegex = $@"(?<=ใน\s*)({DayRegex})";
		public const string RelaxedOnRegex = @"(?<=(ใน|ตอน)\s*)(วัน\s*ที่\s*)((?<day>10th|11th|11st|12nd|12th|13rd|13th|14th|15th|16th|17th|18th|19th|1st|20th|21st|21th|22nd|22th|23rd|23th|24th|25th|26th|27th|28th|29th|2nd|30th|31st|3rd|4th|5th|6th|7th|8th|9th))\b";
		public static readonly string ThisRegex = $@"((สัปดาห์|สัปดา|อาทิตย์|วีค)\s*นี้(\s*(ใน|ตอน))?\s*{WeekDayRegex})|({WeekDayRegex}((\s*ของ)?(\s*(สัปดาห์|สัปดา|อาทิตย์|วีค))?\s*นี้))";
		public static readonly string LastDateRegex = $@"((สัปดาห์|สัปดา|อาทิตย์|วีค)\s*{PastPrefixRegex}(\s*(ใน|ตอน))?\s*{WeekDayRegex})|({WeekDayRegex}((\s*ของ)?(\s*(สัปดาห์|สัปดา|อาทิตย์|วีค))?\s*{PastPrefixRegex}))";
		public static readonly string NextDateRegex = $@"((สัปดาห์|สัปดา|อาทิตย์|วีค)\s*{NextPrefixRegex}(\s*(ใน|ตอน))?\s*{WeekDayRegex})|({WeekDayRegex}((\s*ของ)?(\s*(สัปดาห์|สัปดา|อาทิตย์|วีค))?\s*{NextPrefixRegex}))";
		public static readonly string SpecialDayRegex = $@"(วัน\s*ก่อน\s*(เมื่อ\s*วาน|เมื่อ\s*วาน\s*นี้|มะวาน)|วัน\s*(หลัง|ถัด)\s*จาก\s*พรุ่งนี้|วัน\s*{RelativeRegex}|เมื่อ\s*วาน|มะ\s*วาน|เมื่อ\s*วาน\s*นี้|พรุ่งนี้|วัน\s*นี้|มะรืน|มะ\s*เรื่อง|วาน\s*ซืน|เมื่อ\s*วาน\s*ซืน)";
		public static readonly string SpecialDayWithNumRegex = $@"((?<number>{WrittenNumRegex})\s*วัน\s*(จาก|หลัง\s*จาก|ถัด\s*จาก)\s*(?<day>เมื่อ\s*วาน|มะ\s*วาน|เมื่อ\s*วาน\s*นี้|พรุ่งนี้|วัน\s*นี้|มะรืน|มะ\s*เรื่อง|วาน\s*ซืน|เมื่อ\s*วาน\s*ซืน))";
		public static readonly string RelativeDayRegex = $@"((วัน\s*{RelativeRegex}))";
		public const string SetWeekDayRegex = @"(?<prefix>(ตอน|ใน)\s*)?(?<weekday>เช้า|สาย|บ่าย|เย็น|กลางคืน|คืน|ค่ำ|มืด|ดึก|(วัน\s*)?(อาทิตย์|อาทิต|จันทร์|จัน|อังคาร|พุธ|พุด|พฤหัสบดี|พฤหัส|ศุกร์|เสาร์))";
		public static readonly string WeekDayOfMonthRegex = $@"(?<wom>{WeekDayRegex}\s*(?<cardinal>แรก|ที่\s*(หนึ่ง|1)|ที่\s*(สอง|2)|ที่\s*(สาม|3)|ที่\s*(สี่|4)|ที่\s*(ห้า|5)|สุดท้าย)\s*{MonthSuffixRegex})";
		public static readonly string RelativeWeekDayRegex = $@"({WrittenNumRegex}\s*{WeekDayRegex}\s*((จาก|หลัง\s*จาก|ถัด\s*จาก)\s*นี้|ถัดไป))";
		public static readonly string SpecialDate = $@"(?=(ใน|ตอน)\s*){DayRegex}";
		public static readonly string DateExtractor1 = $@"({WeekDayRegex}\s*(นี้\s*)?[,-]?\s*)?(({DayRegex}(\.)?\s*[/\\\.\-]?\s*{MonthRegex})|({MonthRegex}(\.)?\s*[/\\\.\-]?\s*{DayRegex})|(\({MonthRegex}\s*[-.]\s*{DayRegex}\)))";
		public static readonly string DateExtractor2 = $@"({DateExtractor1})(\s*|\s*,\s*|\s*(ของ|ใน)\s*)({DateYearRegex})";
		public static readonly string DateExtractor3 = $@"({WeekDayRegex}(\s*|\s*,\s*))?{DayRegex}(\.)?(\s*|\s*,\s*|\s*(ของ|ใน)\s*|\s*-\s*){MonthRegex}(\.)?((\s*|\s*,\s*){DateYearRegex})?";
		public static readonly string DateExtractor4 = $@"({MonthNumRegex})\s*[/\\\-]\s*{DayRegex}(\.)?\s*[/\\\-]\s*({DateYearRegex})";
		public static readonly string DateExtractor5 = $@"({DayRegex})\s*[/\\\-\.]\s*{MonthNumRegex}\s*[/\\\-\.]\s*({DateYearRegex})";
		public static readonly string DateExtractor6 = $@"(?<=(ใน|ตอน)\s*){MonthNumRegex}[\-\.]{DayRegex}";
		public static readonly string DateExtractor7 = $@"({MonthNumRegex})\s*/\s*{DayRegex}((\s*|\s*,\s*|\s+(ของ|ใน)\s*){DateYearRegex})?";
		public static readonly string DateExtractor8 = $@"(?<=(ใน|ตอน)\s*){DayRegex}[\\\-]{MonthNumRegex}\b";
		public static readonly string DateExtractor9 = $@"({DayRegex})\s*/\s*{MonthNumRegex}((\s*|\s*,\s*|\s+(ของ|ใน)\s*){DateYearRegex})?";
		public static readonly string DateExtractorA = $@"({DateYearRegex})\s*[/\\\-\.]\s*{MonthNumRegex}\s*[/\\\-\.]\s*{DayRegex}";
		public static readonly string OfMonth = $@"(ของ|ใน)\s*{MonthRegex}";
		public static readonly string MonthEnd = $@"{MonthRegex}";
		public static readonly string WeekDayEnd = $@"{WeekDayRegex}";
		public const string RangeUnitRegex = @"(?<unit>ปี|เดือน|สัปดาห์|สัปดา|อาทิตย์|วีค)";
		public const string OclockRegex = @"(?<oclock>โมง|นาฬิกา|น.|น)";
		public static readonly string DescRegex = $@"((({OclockRegex}\s*)?(?<desc>ampm|am\b|a\.m\.|a m\b|a\. m\.|a\.m\b|a\. m\b|a m\b|pm\b|p\.m\.|p m\b|p\. m\.|p\.m\b|p\. m\b|p\b|p m\b|เช้า|เย็น))|{OclockRegex})";
		public const string HourNumRegex = @"(?<hournum>ศูนย์|หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า|สิบ|สิบ\s*เอ็ด|สิบ\s*สอง|สิบ\s*สาม|สิบ\s*สี่|สิบ\s*ห้า|สิบ\s*หก|สิบ\s*เจ็ด|สิบ\s*แปด|สิบ\s*เก้า|ยี่\s*สิบ|ยี่\s*สิบ\s*เอ็ด|ยี่\s*สิบ\s*สอง|ยี่\s*สิบ\s*สาม)";
		public const string MinuteNumRegex = @"(?<minnum>เอ็ด|หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า|สิบ|สิบ\s*เอ็ด|สิบ\s*สอง|สิบ\s*สาม|สิบ\s*สี่|สิบ\s*ห้า|สิบ\s*หก|สิบ\s*เจ็ด|สิบ\s*แปด|สิบ\s*เก้า|ยี่\s*สิบ|สาม\s*สิบ|สี่\s*สิบ|ห้า\s*สิบ)";
		public const string DeltaMinuteNumRegex = @"(?<deltaminnum>เอ็ด|หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า|สิบ|สิบ\s*เอ็ด|สิบ\s*สอง|สิบ\s*สาม|สิบ\s*สี่|สิบ\s*ห้า|สิบ\s*หก|สิบ\s*เจ็ด|สิบ\s*แปด|สิบ\s*เก้า|ยี่\s*สิบ|สาม\s*สิบ|สี่\s*สิบ|ห้า\s*สิบ)";
		public const string PmRegex = @"(?<pm>(((เวลา|ตอน|ประมาณ|ราว\s*ๆ\s*|เมื่อ|ยาม)\s*)?(บ่าย|เย็น|เที่ยงคืน|เที่ยง|เที่ยง\s*วัน|กลางวัน))|((เวลา|ตอน|ยาม)\s*(กลางคืน|คืน|มืด|ดึก|ค่ำ|หัว\s*ค่ำ)))";
		public const string PmRegexFull = @"(?<pm>((เวลา|ตอน|ประมาณ|ราว\s*ๆ\s*|เมื่อ|ยาม)\s*)?(บ่าย|เย็น|เที่ยงคืน|เที่ยง|เที่ยง\s*วัน|กลางวัน))";
		public const string AmRegex = @"(?<am>((เวลา|ตอน|ประมาณ|ราว\s*ๆ\s*|เมื่อ|ยาม)\s*)?(เช้า|เช้า\s*มืด|เช้า\s*ตรู่|สาย|ก่อน\s*เที่ยง|รุ่ง\s*สาง))";
		public const string LunchRegex = @"(เที่ยง|กลางวัน)";
		public const string NightRegex = @"(เที่ยงคืน|กลางคืน|คืน|มืด|ดึก|ค่ำ|หัว\s*ค่ำ)";
		public const string CommonDatePrefixRegex = @"^[\.]";
		public static readonly string LessThanOneHour = $@"(?<lth>หนึ่ง\s*ใน\s*สี่|สาม\s*ใน\s*สี่|ครึ่ง(\s*ชั่วโมง)?|{BaseDateTime.DeltaMinuteRegex}(\s*นาที)|{DeltaMinuteNumRegex}(\s*นาที))";
		public static readonly string WrittenTimeRegex = $@"(?<writtentime>{HourNumRegex}\s*({MinuteNumRegex}|(?<tens>สิบ|ยี่\s*สิบ|สาม\s*สิบ|สี่\s*สิบ|ห้า\s*สิบ)\s*{MinuteNumRegex}))";
		public static readonly string TimePrefix = $@"(?<prefix>({LessThanOneHour}\s*ที่\s*ผ่าน\s*มา|(อีก\s*)?{LessThanOneHour}(\s*ถึง)?))";
		public static readonly string TimeSuffix = $@"(?<suffix>{AmRegex}|{PmRegex}|{OclockRegex})";
		public static readonly string TimeSuffixFull = $@"(?<suffix>{AmRegex}|{PmRegexFull}|{OclockRegex})";
		public static readonly string BasicTime = $@"(?<basictime>{WrittenTimeRegex}|{HourNumRegex}|{BaseDateTime.HourRegex}:{BaseDateTime.MinuteRegex}(:{BaseDateTime.SecondRegex})?|{BaseDateTime.HourRegex})";
		public const string MidnightRegex = @"(?<midnight>เที่ยงคืน)";
		public const string MidmorningRegex = @"(?<midmorning>สาย|สาย\s*ๆ\s*)";
		public const string MidafternoonRegex = @"(?<midafternoon>บ่าย\s*ๆ\s*|บ่าย\s*แก่\s*ๆ\s*|บ่าย\s*อ่อน\s*ๆ\s*|บ่าย\s*จัด)";
		public const string MiddayRegex = @"(?<midday>กลางวัน|เที่ยง|เที่ยง\s*วัน|เที่ยง\s*ตรง|(12\s*โมง\s*)?เที่ยง)";
		public static readonly string MidTimeRegex = $@"(?<mid>({MidnightRegex}|{MidmorningRegex}|{MidafternoonRegex}|{MiddayRegex}))";
		public static readonly string AtRegex = $@"(((?<=(ตอน|เวลา)\s*)({WrittenTimeRegex}|{HourNumRegex}|{BaseDateTime.HourRegex}|{MidTimeRegex}))|{MidTimeRegex})";
		public static readonly string IshRegex = $@"((ราว|ราว\s*ๆ\s*|ประมาณ)\s*{BaseDateTime.HourRegex}|ประมาณ\s*เที่ยง|ราว\s*เที่ยง|ราว\s*ๆ\s*เที่ยง)";
		public const string TimeUnitRegex = @"([^A-Za-zก-๙]{1,})(?<unit>ชั่วโมง|ช.ม.|ชม.|ช.ม|ชม|นาที|วินาที)";
		public const string RestrictedTimeUnitRegex = @"(?<unit>ชั่วโมง|นาที)";
		public const string FivesRegex = @"(?<tens>(สิบ\s*ห้า|ยี่\s*สิบ(\s*ห้า)?|สาม\s*สิบ(\s*ห้า)?|สี่\s*สิบ(\s*ห้า)?|ห้า\s*สิบ(\s*ห้า)?|สิบ|ห้า))";
		public static readonly string HourRegex = $@"({BaseDateTime.HourRegex})";
		public const string PeriodHourNumRegex = @"(?<hour>ยี่\s*สิบ\s*เอ็ด|ยี่\s*สิบ\s*สอง|ยี่\s*สิบ\s*สาม|ยี่\s*สิบ\s*สี่|ศูนย์|หนึ่ง|สอง|สาม|สี่|ห้า|หก|เจ็ด|แปด|เก้า|สิบ|สิบ\s*เอ็ด|สิบ\s*สอง|สิบ\s*สาม|สิบ\s*สี่|สิบ\s*ห้า|สิบ\s*หก|สิบ\s*เจ็ด|สิบ\s*แปด|สิบ\s*เก้า|ยี่\s*สิบ)";
		public static readonly string ConnectNumRegex = $@"{BaseDateTime.HourRegex}(?<min>00|01|02|03|04|05|06|07|08|09|10|11|12|13|14|15|16|17|18|19|20|21|22|23|24|25|26|27|28|29|30|31|32|33|34|35|36|37|38|39|40|41|42|43|44|45|46|47|48|49|50|51|52|53|54|55|56|57|58|59)\s*{DescRegex}";
		public static readonly string TimeRegex1 = $@"({TimePrefix}\s*)?({WrittenTimeRegex}|{HourNumRegex}|{BaseDateTime.HourRegex})\s*{DescRegex}";
		public static readonly string TimeRegex2 = $@"({TimePrefix}\s*)?(T)?{BaseDateTime.HourRegex}(\s*)?:(\s*)?{BaseDateTime.MinuteRegex}((\s*)?:(\s*)?{BaseDateTime.SecondRegex})?((\s*{DescRegex}))";
		public static readonly string TimeRegex3 = $@"({TimePrefix}\s*)?{BaseDateTime.HourRegex}\.{BaseDateTime.MinuteRegex}(\s*{DescRegex})";
		public static readonly string TimeRegex4 = $@"({TimePrefix})\s*{BasicTime}(\s*{DescRegex})?\s*{TimeSuffix}";
		public static readonly string TimeRegex5 = $@"({TimePrefix})\s*{BasicTime}((\s*{DescRegex}))";
		public static readonly string TimeRegex6 = $@"{BasicTime}(\s*{DescRegex})?\s*{TimeSuffix}";
		public static readonly string TimeRegex7 = $@"({TimeSuffixFull})\s*(ตอน|เวลา)\s*{BasicTime}((\s*{DescRegex}))";
		public static readonly string TimeRegex8 = $@"({TimeSuffixFull})\s*{BasicTime}((\s*{DescRegex}))";
		public static readonly string TimeRegex9 = $@"({PeriodHourNumRegex})\s*{FivesRegex}((\s*{DescRegex}))";
		public static readonly string TimeRegex10 = $@"({TimePrefix}\s*)?{BaseDateTime.HourRegex}(\s*(โมง|นาฬิกา|น|น.)\s*){BaseDateTime.MinuteRegex}(\s*{DescRegex})?";
		public static readonly string PureNumFromTo = $@"((จาก|ตั้งแต่|ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)?({HourRegex}|{PeriodHourNumRegex})(\s*(?<leftDesc>{DescRegex}))?\s*{TillRegex}\s*({HourRegex}|{PeriodHourNumRegex})\s*(?<rightDesc>{PmRegex}|{AmRegex}|{DescRegex})?";
		public static readonly string SpecificTimeFromTo = $@"((จาก|ตั้งแต่|ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)?(?<time1>({TimeRegex2}|({HourRegex}|{PeriodHourNumRegex})(\s*(?<leftDesc>{DescRegex}))?))\s*{TillRegex}\s*(?<time2>({TimeRegex2}|({HourRegex}|{PeriodHourNumRegex})(\s*(?<rightDesc>{DescRegex}))?))";
		public static readonly string SpecificTimeBetweenAnd = $@"(ระหว่าง|ช่วง|ระหว่าง\s*ช่วง\s*)(?<time1>({TimeRegex2}|({HourRegex}|{PeriodHourNumRegex})(\s*(?<leftDesc>{DescRegex}))?))\s*{RangeConnectorRegex}\s*(?<time2>({TimeRegex2}|({HourRegex}|{PeriodHourNumRegex})(\s*(?<rightDesc>{DescRegex}))?))";
		public static readonly string PureNumBetweenAnd = $@"((ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*)({HourRegex}|{PeriodHourNumRegex})(\s*(?<leftDesc>{DescRegex}))?\s*{RangeConnectorRegex}\s*({HourRegex}|{PeriodHourNumRegex})\s*(?<rightDesc>{PmRegex}|{AmRegex}|{DescRegex})?";
		public const string PrepositionRegex = @"(?<prep>^(ที่|ตอน|เวลา|ณ\s*เวลา)$)";
		public const string TimeOfDayRegex = @"(?<timeOfDay>(((ใน\s*ช่วง|ช่วง|ตอน|ใน\s*ตอน|เวลา)\s*)?(เช้า(\s*(ตรู่|มืด))?|สาย(\s*โด่ง)?|บ่าย(\s*(อ่อน|จัด|แก่))?|(หัว\s*)?ค่ำ|กลางคืน|คืน|เย็น|กลางวัน|ระหว่าง\s*วัน)))";
		public static readonly string SpecificTimeOfDayRegex = $@"(({TimeOfDayRegex}\s*{StrictRelativeRegex})|คืน\s*นี้)";
		public static readonly string TimeFollowedUnit = $@"({TimeUnitRegex})";
		public static readonly string TimeNumberCombinedWithUnit = $@"(?<num>\d+(\.\d*)?){TimeUnitRegex}";
		public const string NowRegex = @"(?<now>(ณ\s*)?(ตอนนี้|เวลานี้|บัดนี้|ขณะนี้|เดี๋ยวนี้|ปัจจุบัน)|(ด่วน|เร็ว)\s*ที่\s*สุด\s*ที่\s*เป็นไป\s*ได้|asap|(เมื่อ\s*)?ไม่\s*นาน\s*มา\s*นี้|(เมื่อ\s*)?เร็ว\s*ๆ\s*นี้|ก่อน\s*หน้า\s*นี้)";
		public const string SuffixRegex = @"((ใน\s*ช่วง|ช่วง|ตอน|ใน\s*ตอน|เวลา)\s*)?(เช้า|สาย|บ่าย|เย็น|ค่ำ|กลางคืน|คืน)";
		public const string DateTimeTimeOfDayRegex = @"(?<timeOfDay>เช้า|สาย|บ่าย|เย็น|ค่ำ|กลางคืน|คืน)";
		public static readonly string DateTimeSpecificTimeOfDayRegex = $@"(({DateTimeTimeOfDayRegex}\s*{RelativeRegex})|คืน\s*นี้)";
		public static readonly string TimeOfTodayAfterRegex = $@"(,\s*)?((ใน\s*ช่วง|ช่วง|ตอน|ใน\s*ตอน|เวลา)\s*)?{DateTimeSpecificTimeOfDayRegex}";
		public static readonly string TimeOfTodayBeforeRegex = $@"{DateTimeSpecificTimeOfDayRegex}(\s*,)?(\s*(ตอน|ใน\s*ตอน|ช่วง|ใน\s*ช่วง|เวลา|ใน\s*เวลา)(ประมาณ|ราว)?)?";
		public static readonly string SimpleTimeOfTodayAfterRegex = $@"({HourNumRegex}|{BaseDateTime.HourRegex})\s*(,\s*)?((ใน\s*ช่วง|ช่วง|ตอน|ใน\s*ตอน|เวลา)\s*)?{DateTimeSpecificTimeOfDayRegex}";
		public static readonly string SimpleTimeOfTodayBeforeRegex = $@"{DateTimeSpecificTimeOfDayRegex}(\s*,)?(\s*(ตอน|ใน\s*ตอน|ช่วง|ใน\s*ช่วง|เวลา|ใน\s*เวลา)(ประมาณ|ราว)?)?\s*({HourNumRegex}|{BaseDateTime.HourRegex})";
		public const string TheEndOfRegex = @"(สิ้น|จบ)";
		public const string PeriodTimeOfDayRegex = @"(((ใน\s*ช่วง|ช่วง|ตอน|ใน\s*ตอน|เวลา)\s*)?(?<timeOfDay>เช้า(\s*(ตรู่|มืด))?|สาย(\s*โด่ง)?|บ่าย(\s*(อ่อน|จัด|แก่))?|(หัว\s*)?ค่ำ|กลางคืน|คืน|เย็น))";
		public static readonly string PeriodSpecificTimeOfDayRegex = $@"(({StrictRelativeRegex}\s*{PeriodTimeOfDayRegex})|คืน\s*นี้)";
		public static readonly string PeriodTimeOfDayWithDateRegex = $@"(({TimeOfDayRegex}(\s*(ตอน|ของ))?))";
		public const string LessThanRegex = @"(น้อย\s*กว่า)";
		public const string MoreThanRegex = @"(มาก\s*กว่า)";
		public const string DurationUnitRegex = @"(?<unit>ปี|เดือน|สัปดาห์|สัปดา|อาทิตย์|วีค|วัน|ชั่วโมง|ช.ม.|ชม.|ช.ม|ชม|นาที|วินาที)";
		public const string SuffixAndRegex = @"(?<suffix>\s*(และ|กับ|กับ\s*อีก)\s*(?<suffix_num>ครึ่ง|หนึ่ง\s*ใน\s*สี่))";
		public const string PeriodicRegex = @"(?<periodic>ราย\s*วัน|ประจำ\s*วัน|ราย\s*เดือน|ประจำ\s*เดือน|ราย\s*สัปดาห์|ราย\s*สัปดา|ประจำ\s*สัปดาห์|ประจำ\s*สัปดา|ราย\s*อาทิตย์|ทุก\s*สอง\s*สัปดาห์|ทุก\s*สอง\s*สัปดา|ทุก\s*สอง\s*อาทิตย์|ราย\s*ปี|ประจำ\s*ปี)";
		public static readonly string EachUnitRegex = $@"(?<each>((แต่\s*ละ|ทุก|ทุก\s*ๆ\s*)\s*{DurationUnitRegex})|ปี\s*เว้น\s*ปี|เดือน\s*เว้น\s*เดือน|อาทิตย์\s*เว้น\s*อาทิตย์|สัปดาห์\s*เว้น\s*สัปดาห์|สัปดา\s*เว้น\s*สัปดา|วัน\s*เว้น\s*วัน|ชั่วโมง\s*เว้น\s*ชั่วโมง|นาที\s*เว้น\s*นาที)";
		public const string EachPrefixRegex = @"(?<each>(แต่\s*ละ|(ทุก|ทุก\s*ๆ)))";
		public const string SetEachRegex = @"(?<each>(แต่\s*ละ|(ทุก|ทุก\s*ๆ))\s*)";
		public const string SetLastRegex = @"(?<last>หน้า|ถัดไป|ต่อไป|ที่\s*จะ\s*ถึง|ที่\s*กำลัง\s*จะ\s*ถึง|ที่\s*จะ\s*มา\s*ถึง|ที่\s*กำลัง\s*จะ\s*มา\s*ถึง|ก่อน\s*หน้า|ก่อน|ที่\s*แล้ว|ที่\s*ผ่าน\s*มา|นี้|ปัจจุบัน)";
		public const string EachDayRegex = @"(แต่\s*ละ|(ทุก|ทุก\s*ๆ))\s*วัน";
		public static readonly string DurationFollowedUnit = $@"({SuffixAndRegex})?(\s*|-)?({DurationUnitRegex})";
		public static readonly string NumberCombinedWithDurationUnit = $@"(?<num>\d+(\.\d*)?)(-)?{DurationUnitRegex}";
		public static readonly string AnUnitRegex = $@"((?<half>ครึ่ง\s*)?|หนึ่ง|อีก\s*หนึ่ง)\s*{DurationUnitRegex}";
		public const string DuringRegex = @"(ระหว่าง)\s*(?<unit>ปี|เดือน|สัปดาห์|สัปดา|อาทิตย์|วีค|วัน)";
		public const string AllRegex = @"(?<all>(ตลอด|ทั้ง|ตลอด\s*ทั้ง)\s*(?<unit>ปี|เดือน|สัปดาห์|สัปดา|อาทิตย์|วีค|วัน))";
		public const string HalfRegex = @"(?<half>ครึ่ง\s*(?<unit>ปี|เดือน|สัปดาห์|สัปดา|อาทิตย์|วีค|วัน|ชั่วโมง|ชม.|ช.ม.|ช.ม|ชม))";
		public const string ConjunctionRegex = @"((กับ(\s*อีก)?)|และ(\s*อีก)?)";
		public const string DateTokenPrefix = "ใน ";
		public const string TimeTokenPrefix = "ตอน ";
		public const string TokenBeforeDate = "ใน ";
		public const string TokenBeforeTime = "ตอน ";
		public const string AMTimeRegex = @"(?<am>เช้า|สาย)";
		public const string PMTimeRegex = @"(?<pm>บ่าย|เย็น|กลางคืน|คืน|ค่ำ|หัว\s*ค่ำ)";
		public const string InclusiveModPrepositions = @"(?<include>((ตอน|ใน|เวลา)\s*หรือ\s*)|(\s*หรือ\s*(ตอน|ใน|เวลา)))";
		public static readonly string BeforeRegex = $@"({InclusiveModPrepositions})?(ก่อน|ล่วงหน้า|ก่อน\s*หน้า|(ไม่\s*(เกิน|ช้า)\s*กว่า|ก่อน\s*ถึง|เร็ว\s*กว่า)|จบ\s*(ตอน|ใน)|ภายใน|ถึง|จนถึง|ไป\s*จนถึง|จน\s*กระทั่ง){InclusiveModPrepositions}?";
		public static readonly string AfterRegex = $@"({InclusiveModPrepositions})?((หลัง|ภาย\s*หลัง)|(?<!ไม่\s*)(เกิน|ช้า)\s*กว่า){InclusiveModPrepositions}?";
		public const string SinceRegex = @"(ตั้งแต่|เริ่ม(\s*ต้น)?\s*(จาก|ตอน|ใน|เมื่อ))";
		public const string AgoRegex = @"((ที่\s*แล้ว|ที่\s*ผ่าน\s*มา)|ก่อน(\s*หน้า)?\s*(?<day>(วัน\s*)?เมื่อวาน(\s*นี้)?|วัน\s*นี้))";
		public const string LaterRegex = @"(ต่อไป|ถัดไป|ข้าง\s*หน้า|(ถัด|ต่อ)\s*จาก\s*นี้|ต่อไปนี้|หลัง(\s*จาก)?)(?<day>(วัน\s*)?พรุ่งนี้|วัน\s*นี้)";
		public const string InConnectorRegex = @"ใน";
		public static readonly string WithinNextPrefixRegex = $@"(ภายใน\s*({WrittenMonthRegex}|{DateUnitRegex}|{RangeUnitRegex}|{DurationUnitRegex}|{WeekDayRegex}|{SingleWeekDayRegex})(\s*{NextPrefixRegex})?)";
		public const string AmPmDescRegex = @"(ampm)";
		public static readonly string MorningStartEndRegex = $@"(^(เช้า|{AmDescRegex}))|((เช้า|{AmDescRegex})$)";
		public static readonly string AfternoonStartEndRegex = $@"(บ่าย|{PmDescRegex})";
		public const string EveningStartEndRegex = @"(^(เย็น))|((เย็น)$)";
		public const string NightStartEndRegex = @"(^(ข้ามคืน|คืน\s*นี้|กลางคืน|คืน|ค่ำ|ดึก))|((ข้ามคืน|คืน\s*นี้|กลางคืน|คืน|ค่ำ|ดึก)$)";
		public const string InexactNumberRegex = @"(สอง\s*สาม|2-3|ไม่\s*กี่|(?<NumTwoTerm>สอง\s*ถึง\s*สาม))";
		public static readonly string InexactNumberUnitRegex = $@"({InexactNumberRegex})\s*({DurationUnitRegex})";
		public static readonly string RelativeTimeUnitRegex = $@"(({TimeUnitRegex})\s*({NextPrefixRegex}|{PastPrefixRegex}|{ThisPrefixRegex}))";
		public static readonly string RelativeDurationUnitRegex = $@"((({DurationUnitRegex})(?=({NextPrefixRegex}|{PastPrefixRegex}|{ThisPrefixRegex})\s*))|({RestrictedTimeUnitRegex}))";
		public static readonly string ReferenceDatePeriodRegex = $@"(?<duration>สัปดาห์|สัปดา|อาทิตย์|วีค|เดือน|ปี|สุด\s*สัปดาห์|สุด\s*สัปดา)\s*({ReferencePrefixRegex})";
		public const string ConnectorRegex = @"^(-|,|เป็น\s*เวลา|ประมาณ)$";
		public const string FromToRegex = @"(จาก|ตั้งแต่).+(ถึง).+";
		public const string SingleAmbiguousMonthRegex = @"^(มค|กพ|มีค|พค|กค|กย|สค|ตค|พย)$";
		public const string SingleAmbiguousTermsRegex = @"^(วัน|สัปดาห์|อาทิตย์|วีค|เดือน|ปี)$";
		public const string PrepositionSuffixRegex = @"(ใน|ตอน|เวลา|ราว|ประมาณ|จาก|ตั้งแต่|ถึง)$";
		public const string FlexibleDayRegex = @"(?<DayOfMonth>([A-Za-zก-๙]+\s*)?[A-Za-zก-๙\d]+)";
		public static readonly string ForTheRegex = $@"(((ตอน\s*(วัน\s*ที่\s*)?{FlexibleDayRegex})|(ใน\s*(\s*วัน\s*ที่)?{FlexibleDayRegex}(?<=(st|nd|rd|th))))(?<end>\s*(,|\.|!|\?|$)))";
		public static readonly string WeekDayAndDayOfMonthRegex = $@"({WeekDayRegex})\s*({FlexibleDayRegex})";
		public const string RestOfDateRegex = @"ที่\s*เหลือ\s*ของ\s*(?<duration>สัปดาห์|สัปดา|อาทิตย์|วีค|เดือน|ปี)(\s*(นี้|ปัจจุบัน))?";
		public const string RestOfDateTimeRegex = @"ที่\s*เหลือ\s*ของ\s*(?<unit>วัน)(\s*นี้)?";
		public const string MealTimeRegex = @"((ตอน|เวลา)\s*)?(?<mealTime>เที่ยง|กลางวัน)";
		public static readonly string NumberEndingPattern = $@"^(\s*(?<meeting>ประชุม|นัด\s*หมาย|การ\s*ประชุม|โทรศัพท์|skype call|สไกป์)\s*ถึง\s*(?<newTime>{PeriodHourNumRegex}|{HourRegex})((\.)?$|(\.,|,|!|\?)))";
		public const string OneOnOneRegex = @"(1\s*:\s*1)|(หนึ่ง\s*(ต่อ\s*)?หนึ่ง|ตัว\s*(ต่อ\s*)?ตัว|หนึ่ง\s*-\s*หนึ่ง|หนึ่ง\s*:\s*หนึ่ง)";
		public static readonly string LaterEarlyPeriodRegex = $@"({PrefixPeriodRegex})\s*(?<suffix>{OneWordPeriodRegex})";
		public static readonly string WeekWithWeekDayRangeRegex = $@"((?<week>(สัปดาห์|สัปดา|อาทิตย์|วีค)\s*({NextPrefixRegex}|{PastPrefixRegex}|นี้))((\s*(ระหว่าง|ช่วง|ระหว่าง\s*ช่วง)\s*{WeekDayRegex}\s*(และ|กับ|ถึง)\s*{WeekDayRegex})|(\s*(จาก|ตั้งแต่)\s*{WeekDayRegex}\s*(จน(ถึง\s*)?)\s*{WeekDayRegex})))\b";
		public const string GeneralEndingRegex = @"((\.,)|\.|,|!|\?)";
		public const string MiddlePauseRegex = @"\s*(,)\s*";
		public const string DurationConnectorRegex = @"(?<connector>\s*|(และ|กับ|กับ\s*อีก)|,)";
		public const string PrefixArticleRegex = @"the\s*";
		public const string OrRegex = @"((,\s*)(หรือ|และ|กับ|กับ\s*อีก)|,)";
		public static readonly string YearPlusNumberRegex = $@"(ปี\s*((?<year>(\d{{3,4}}))|{FullTextYearRegex}))";
		public static readonly string NumberAsTimeRegex = $@"({WrittenTimeRegex}|{PeriodHourNumRegex}|{BaseDateTime.HourRegex})";
		public static readonly string TimeBeforeAfterRegex = $@"(((?<=(ก่อน|ไม่\s*ช้า\s*กว่า|ไม่\s*เกิน|ภาย\s*ใน|หลัง(\s*จาก)?)\s*)({WrittenTimeRegex}|{HourNumRegex}|{BaseDateTime.HourRegex}|{MidTimeRegex}))|{MidTimeRegex})";
		public const string DateNumberConnectorRegex = @"(?<connector>\s*(ตอน|ณ\s*เวลา|เวลา|ช่วง))";
		public const string DecadeRegex = @"(?<decade>ยุค\s*ปี\s*หนึ่ง\s*พัน\s*เก้า\s*ร้อย|ยุค\s*ปี\s*พัน\s*เก้า\s*ร้อย|ยุค\s*10|ยุค\s*20|ยุค\s*30|ยุค\s*40|ยุค\s*50|ยุค\s*60|ยุค\s*70|ยุค\s*80|ยุค\s*90|ทเวนตี้|ทเวนตี้ส์|เธอร์ตี้|เธอร์ตี้ส์|โฟร์ตี้|โฟร์ตี้ส์|ฟิฟตี้|ฟิฟตี้ส์|ซิกส์ตี้|ซิกตี้|ซิกซ์ตี้ส์|ซิกตี้ส์|เซเวนตี้|เซเวนตี้ส์|เอทตี้|เอ็ทตี้|เอทตี้ส์|เอ็ทตี้ส์|ไนน์ตี้|ไนน์ตี้ส์|ยุค\s*ปี\s*สอง\s*พัน)";
		public static readonly string DecadeWithCenturyRegex = $@"((ยุค|ปี|ช่วง\s*ปี)\s*)?(((?<century>\d|1\d|2\d)?(')?(?<decade>\d0)(')?s?)|(({CenturyRegex}(\s*|-)((กับ|และ|ถึง)\s*)?)?{DecadeRegex}))";
		public static readonly string RelativeDecadeRegex = $@"(((?<number>[\w,]*)\s*)?(ทศวรรษ|รอบสิบปี)\s*{RelativeRegex})";
		public const string YearAfterRegex = @"(หรือ\s*(เลย\s*จาก\s*นั้น|หลัง\s*จาก\s*นั้น))";
		public static readonly string YearPeriodRegex = $@"(((จาก|ระหว่าง|(ใน\s*)?(ปี|ช่วง))\s*)?{YearRegex}\s*({TillRegex}|{RangeConnectorRegex})\s*{YearRegex})";
		public static readonly string ComplexDatePeriodRegex = $@"((จาก|ระหว่าง|(ใน\s*)?(ปี|ช่วง))\s*)?(?<start>.+)\s*({TillRegex}|{RangeConnectorRegex})\s*(?<end>.+)";
		public static readonly Dictionary<string, string> UnitMap = new Dictionary<string, string>
		{
			{ "ปี", "Y" },
			{ "เดือน", "MON" },
			{ "สัปดาห์", "W" },
			{ "สัปดา", "W" },
			{ "อาทิตย์", "W" },
			{ "วีค", "W" },
			{ "วัน", "D" },
			{ "ชั่วโมง", "H" },
			{ "ชม.", "H" },
			{ "ช.ม.", "H" },
			{ "ช.ม", "H" },
			{ "ชม", "H" },
			{ "นาที", "M" },
			{ "วินาที", "S" }
		};
		public static readonly Dictionary<string, long> UnitValueMap = new Dictionary<string, long>
		{
			{ "ปี", 31536000 },
			{ "เดือน", 2592000 },
			{ "สัปดาห์", 604800 },
			{ "สัปดา", 604800 },
			{ "อาทิตย์", 604800 },
			{ "วีค", 604800 },
			{ "วัน", 86400 },
			{ "ชั่วโมง", 3600 },
			{ "ชม.", 3600 },
			{ "ช.ม.", 3600 },
			{ "ช.ม", 3600 },
			{ "ชม", 3600 },
			{ "นาที", 60 },
			{ "วินาที", 1 }
		};
		public static readonly Dictionary<string, string> SeasonMap = new Dictionary<string, string>
		{
			{ "ฤดูใบไม้ผลิ", "SP" },
			{ "ฤดูร้อน", "SU" },
			{ "ฤดูฝน", "RA" },
			{ "ฤดูใบไม้ร่วง", "FA" },
			{ "ฤดูหนาว", "WI" }
		};
		public static readonly Dictionary<string, int> SeasonValueMap = new Dictionary<string, int>
		{
			{ "SP", 3 },
			{ "SU", 6 },
			{ "RA", 5 },
			{ "FA", 9 },
			{ "WI", 12 }
		};
		public static readonly Dictionary<string, int> CardinalMap = new Dictionary<string, int>
		{
			{ "แรก", 1 },
			{ "ที่หนึ่ง", 1 },
			{ "ที่สอง", 2 },
			{ "ที่สาม", 3 },
			{ "ที่สี่", 4 },
			{ "ที่ห้า", 5 },
			{ "ที่ 1", 1 },
			{ "ที่ 2", 2 },
			{ "ที่ 3", 3 },
			{ "ที่ 4", 4 },
			{ "ที่ 5", 5 }
		};
		public static readonly Dictionary<string, int> DayOfWeek = new Dictionary<string, int>
		{
			{ "วันจันทร์", 1 },
			{ "วันจัน", 1 },
			{ "วันอังคาร", 2 },
			{ "วันพุธ", 3 },
			{ "วันพุด", 3 },
			{ "วันพฤหัสบดี", 4 },
			{ "วันพฤหัส", 4 },
			{ "วันศุกร์", 5 },
			{ "วันศุก", 5 },
			{ "วันสุก", 5 },
			{ "วันเสาร์", 6 },
			{ "วันเสา", 6 },
			{ "วันอาทิตย์", 0 },
			{ "วันอาทิต", 0 },
			{ "วันอาทิด", 0 },
			{ "จันทร์", 1 },
			{ "จัน", 1 },
			{ "อังคาร", 2 },
			{ "พุธ", 3 },
			{ "พุด", 3 },
			{ "พฤหัสบดี", 4 },
			{ "พฤหัส", 4 },
			{ "ศุกร์", 5 },
			{ "ศุก", 5 },
			{ "เสาร์", 6 },
			{ "อาทิตย์", 0 },
			{ "อาทิด", 0 },
			{ "จ.", 1 },
			{ "อ.", 2 },
			{ "พ.", 3 },
			{ "พฤ.", 4 },
			{ "ศ.", 5 },
			{ "ส.", 6 },
			{ "อา.", 0 },
			{ "วันจ.", 1 },
			{ "วันอ.", 2 },
			{ "วันพ.", 3 },
			{ "วันพฤ.", 4 },
			{ "วันศ.", 5 },
			{ "วันส.", 6 },
			{ "วันอา.", 0 }
		};
		public static readonly Dictionary<string, int> MonthOfYear = new Dictionary<string, int>
		{
			{ "มกราคม", 1 },
			{ "กุมภาพันธ์", 2 },
			{ "มีนาคม", 3 },
			{ "เมษายน", 4 },
			{ "พฤษภาคม", 5 },
			{ "มิถุนายน", 6 },
			{ "กรกฎาคม", 7 },
			{ "สิงหาคม", 8 },
			{ "กันยายน", 9 },
			{ "ตุลาคม", 10 },
			{ "พฤศจิกายน", 11 },
			{ "ธันวาคม", 12 },
			{ "เดือนมกราคม", 1 },
			{ "เดือนกุมภาพันธ์", 2 },
			{ "เดือนมีนาคม", 3 },
			{ "เดือนเมษายน", 4 },
			{ "เดือนพฤษภาคม", 5 },
			{ "เดือนมิถุนายน", 6 },
			{ "เดือนกรกฎาคม", 7 },
			{ "เดือนสิงหาคม", 8 },
			{ "เดือนกันยายน", 9 },
			{ "เดือนตุลาคม", 10 },
			{ "เดือนพฤศจิกายน", 11 },
			{ "เดือนธันวาคม", 12 },
			{ "มกรา", 1 },
			{ "เดือนมกรา", 1 },
			{ "กุมภา", 2 },
			{ "เดือนกุมภา", 2 },
			{ "มีนา", 3 },
			{ "เดือนมีนา", 3 },
			{ "เมษา", 4 },
			{ "เดือนเมษา", 4 },
			{ "พฤษภา", 5 },
			{ "เดือนพฤษภา", 5 },
			{ "มิถุนา", 6 },
			{ "เดือนมิถุนา", 6 },
			{ "กรกฎา", 7 },
			{ "เดือนกรกฎา", 7 },
			{ "สิงหา", 8 },
			{ "เดือนสิงหา", 8 },
			{ "กันยา", 9 },
			{ "เดือนกันยา", 9 },
			{ "ตุลา", 10 },
			{ "เดือนตุลา", 10 },
			{ "พฤศจิกา", 11 },
			{ "เดือนพฤศจิกา", 11 },
			{ "พฤศจิ", 11 },
			{ "เดือนพฤศจิ", 11 },
			{ "ธันวา", 12 },
			{ "เดือนธันวา", 12 },
			{ "ม.ค.", 1 },
			{ "ก.พ.", 2 },
			{ "มี.ค.", 3 },
			{ "เม.ย.", 4 },
			{ "พ.ค.", 5 },
			{ "มิ.ย.", 6 },
			{ "ก.ค.", 7 },
			{ "ส.ค.", 8 },
			{ "ก.ย.", 9 },
			{ "ต.ค.", 10 },
			{ "พ.ย.", 11 },
			{ "ธ.ค.", 12 },
			{ "ม.ค", 1 },
			{ "ก.พ", 2 },
			{ "มี.ค", 3 },
			{ "เม.ย", 4 },
			{ "พ.ค", 5 },
			{ "มิ.ย", 6 },
			{ "ก.ค", 7 },
			{ "ส.ค", 8 },
			{ "ก.ย", 9 },
			{ "ต.ค", 10 },
			{ "พ.ย", 11 },
			{ "ธ.ค", 12 },
			{ "มค.", 1 },
			{ "กพ.", 2 },
			{ "มีค.", 3 },
			{ "เมย.", 4 },
			{ "พค.", 5 },
			{ "มิย.", 6 },
			{ "กค.", 7 },
			{ "สค.", 8 },
			{ "กย.", 9 },
			{ "ตค.", 10 },
			{ "พย.", 11 },
			{ "ธค.", 12 },
			{ "มค", 1 },
			{ "กพ", 2 },
			{ "มีค", 3 },
			{ "เมย", 4 },
			{ "พค", 5 },
			{ "มิย", 6 },
			{ "กค", 7 },
			{ "สค", 8 },
			{ "กย", 9 },
			{ "ตค", 10 },
			{ "พย", 11 },
			{ "ธค", 12 },
			{ "1", 1 },
			{ "2", 2 },
			{ "3", 3 },
			{ "4", 4 },
			{ "5", 5 },
			{ "6", 6 },
			{ "7", 7 },
			{ "8", 8 },
			{ "9", 9 },
			{ "10", 10 },
			{ "11", 11 },
			{ "12", 12 },
			{ "01", 1 },
			{ "02", 2 },
			{ "03", 3 },
			{ "04", 4 },
			{ "05", 5 },
			{ "06", 6 },
			{ "07", 7 },
			{ "08", 8 },
			{ "09", 9 }
		};
		public static readonly Dictionary<string, int> Numbers = new Dictionary<string, int>
		{
			{ "ศูนย์", 0 },
			{ "หนึ่ง", 1 },
			{ "เอ็ด", 1 },
			{ "สอง", 2 },
			{ "สาม", 3 },
			{ "สี่", 4 },
			{ "ห้า", 5 },
			{ "หก", 6 },
			{ "เจ็ด", 7 },
			{ "แปด", 8 },
			{ "เก้า", 9 },
			{ "สิบ", 10 },
			{ "สิบเอ็ด", 11 },
			{ "สิบสอง", 12 },
			{ "สิบสาม", 13 },
			{ "สิบสี่", 14 },
			{ "สิบห้า", 15 },
			{ "สิบหก", 16 },
			{ "สิบเจ็ด", 17 },
			{ "สิบแปด", 18 },
			{ "สิบเก้า", 19 },
			{ "ยี่สิบ", 20 },
			{ "ยี่สิบเอ็ด", 21 },
			{ "ยี่สิบสอง", 22 },
			{ "ยี่สิบสาม", 23 },
			{ "ยี่สิบสี่", 24 },
			{ "ยี่สิบห้า", 25 },
			{ "ยี่สิบหก", 26 },
			{ "ยี่สิบเจ็ด", 27 },
			{ "ยี่สิบแปด", 28 },
			{ "ยี่สิบเก้า", 29 },
			{ "สามสิบ", 30 },
			{ "สามสิบเอ็ด", 31 },
			{ "สามสิบสอง", 32 },
			{ "สามสิบสาม", 33 },
			{ "สามสิบสี่", 34 },
			{ "สามสิบห้า", 35 },
			{ "สามสิบหก", 36 },
			{ "สามสิบเจ็ด", 37 },
			{ "สามสิบแปด", 38 },
			{ "สามสิบเก้า", 39 },
			{ "สี่สิบ", 40 },
			{ "สี่สิบเอ็ด", 41 },
			{ "สี่สิบสอง", 42 },
			{ "สี่สิบสาม", 43 },
			{ "สี่สิบสี่", 44 },
			{ "สี่สิบห้า", 45 },
			{ "สี่สิบหก", 46 },
			{ "สี่สิบเจ็ด", 47 },
			{ "สี่สิบแปด", 48 },
			{ "สี่สิบเก้า", 49 },
			{ "ห้าสิบ", 50 },
			{ "ห้าสิบเอ็ด", 51 },
			{ "ห้าสิบสอง", 52 },
			{ "ห้าสิบสาม", 53 },
			{ "ห้าสิบสี่", 54 },
			{ "ห้าสิบห้า", 55 },
			{ "ห้าสิบหก", 56 },
			{ "ห้าสิบเจ็ด", 57 },
			{ "ห้าสิบแปด", 58 },
			{ "ห้าสิบเก้า", 59 },
			{ "หกสิบ", 60 },
			{ "หกสิบเอ็ด", 61 },
			{ "หกสิบสอง", 62 },
			{ "หกสิบสาม", 63 },
			{ "หกสิบสี่", 64 },
			{ "หกสิบห้า", 65 },
			{ "หกสิบหก", 66 },
			{ "หกสิบเจ็ด", 67 },
			{ "หกสิบแปด", 68 },
			{ "หกสิบเก้า", 69 },
			{ "เจ็ดสิบ", 70 },
			{ "เจ็ดสิบเอ็ด", 71 },
			{ "เจ็ดสิบสอง", 72 },
			{ "เจ็ดสิบสาม", 73 },
			{ "เจ็ดสิบสี่", 74 },
			{ "เจ็ดสิบห้า", 75 },
			{ "เจ็ดสิบหก", 76 },
			{ "เจ็ดสิบเจ็ด", 77 },
			{ "เจ็ดสิบแปด", 78 },
			{ "เจ็ดสิบเก้า", 79 },
			{ "แปดสิบ", 80 },
			{ "แปดสิบเอ็ด", 81 },
			{ "แปดสิบสอง", 82 },
			{ "แปดสิบสาม", 83 },
			{ "แปดสิบสี่", 84 },
			{ "แปดสิบห้า", 85 },
			{ "แปดสิบหก", 86 },
			{ "แปดสิบเจ็ด", 87 },
			{ "แปดสิบแปด", 88 },
			{ "แปดสิบเก้า", 89 },
			{ "เก้าสิบ", 90 },
			{ "เก้าสิบเอ็ด", 91 },
			{ "เก้าสิบสอง", 92 },
			{ "เก้าสิบสาม", 93 },
			{ "เก้าสิบสี่", 94 },
			{ "เก้าสิบห้า", 95 },
			{ "เก้าสิบหก", 96 },
			{ "เก้าสิบเจ็ด", 97 },
			{ "เก้าสิบแปด", 98 },
			{ "เก้าสิบเก้า", 99 },
			{ "หนึ่งร้อย", 100 }
		};
		public static readonly Dictionary<string, int> DayOfMonth = new Dictionary<string, int>
		{
			{ "1st", 1 },
			{ "วันที่ 1", 1 },
			{ "2nd", 2 },
			{ "วันที่ 2", 2 },
			{ "3rd", 3 },
			{ "วันที่ 3", 3 },
			{ "4th", 4 },
			{ "วันที่ 4", 4 },
			{ "5th", 5 },
			{ "วันที่ 5", 5 },
			{ "6th", 6 },
			{ "วันที่ 6", 6 },
			{ "7th", 7 },
			{ "วันที่ 7", 7 },
			{ "8th", 8 },
			{ "วันที่ 8", 8 },
			{ "9th", 9 },
			{ "วันที่ 9", 9 },
			{ "10th", 10 },
			{ "วันที่ 10", 10 },
			{ "11th", 11 },
			{ "วันที่ 11", 11 },
			{ "11st", 11 },
			{ "วันที่ 12", 12 },
			{ "12th", 12 },
			{ "12nd", 12 },
			{ "วันที่ 13", 13 },
			{ "13th", 13 },
			{ "13rd", 13 },
			{ "วันที่ 14", 14 },
			{ "14th", 14 },
			{ "วันที่ 15", 15 },
			{ "15th", 15 },
			{ "วันที่ 16", 16 },
			{ "16th", 16 },
			{ "วันที่ 17", 17 },
			{ "17th", 17 },
			{ "วันที่ 18", 18 },
			{ "18th", 18 },
			{ "วันที่ 19", 19 },
			{ "19th", 19 },
			{ "วันที่ 20", 20 },
			{ "20th", 20 },
			{ "วันที่ 21", 21 },
			{ "21st", 21 },
			{ "21th", 21 },
			{ "วันที่ 22", 22 },
			{ "22nd", 22 },
			{ "22th", 22 },
			{ "วันที่ 23", 23 },
			{ "23rd", 23 },
			{ "23th", 23 },
			{ "วันที่ 24", 24 },
			{ "24th", 24 },
			{ "วันที่ 25", 25 },
			{ "25th", 25 },
			{ "วันที่ 26", 26 },
			{ "26th", 26 },
			{ "วันที่ 27", 27 },
			{ "27th", 27 },
			{ "วันที่ 28", 28 },
			{ "28th", 28 },
			{ "วันที่ 29", 29 },
			{ "29th", 29 },
			{ "วันที่ 30", 30 },
			{ "30th", 30 },
			{ "วันที่ 31", 31 },
			{ "31st", 31 }
		};
		public static readonly Dictionary<string, double> DoubleNumbers = new Dictionary<string, double>
		{
			{ "ครึ่ง", 0.5 },
			{ "หนึ่งในสี่", 0.25 },
			{ "ไตรมาศ", 0.25 },
			{ "ควอเตอร์", 0.25 },
			{ "ควอร์เตอร์", 0.25 }
		};
		public static readonly Dictionary<string, int> WrittenDecades = new Dictionary<string, int>
		{
			{ "ทเวนตี้", 20 },
			{ "ทเวนตี้ส์", 20 },
			{ "ยุค 20", 20 },
			{ "เธอร์ตี้", 30 },
			{ "เธอร์ตี้ส์", 30 },
			{ "ยุค 30", 30 },
			{ "โฟร์ตี้", 40 },
			{ "โฟร์ตี้ส์", 40 },
			{ "ยุค 40", 40 },
			{ "ฟิฟตี้", 50 },
			{ "ฟิฟตี้ส์", 50 },
			{ "ยุค 50", 50 },
			{ "ซิกตี้", 60 },
			{ "ซิกส์ตี้", 60 },
			{ "ซิกซ์ตี้ส์", 60 },
			{ "ซิกตี้ส์", 60 },
			{ "ยุค 60", 60 },
			{ "เซเวนตี้", 70 },
			{ "เซเวนตี้ส์", 70 },
			{ "ยุค 70", 70 },
			{ "เอทตี้", 80 },
			{ "เอทตี้ส์", 80 },
			{ "ยุค 80", 80 },
			{ "ไนน์ตี้", 90 },
			{ "ไนน์ตี้้ส์", 90 },
			{ "ยุค 90", 90 }
		};
		public static readonly Dictionary<string, int> SpecialDecadeCases = new Dictionary<string, int>
		{
			{ "ยุคปีพันเก้าร้อย", 1900 },
			{ "ยุคปีสองพัน", 2000 }
		};
		public const string DefaultLanguageFallback = "MDY";
		public static readonly string[] DurationDateRestrictions = {  };
	}
}